### ISSUE TITLE
Sending both string and object in one log statement

### ISSUE THREAD

**Issue by serhatcan** [logzio/logzio-nodejs#10]
Hi, I was trying to send log by using a statement like;
**`logger.log('Response: ', response);`**
However, it did not work. It would be nice if it can work like that or maybe a warning should be written in your docs. I know your docs say it expects string or an object. 

However, as Javascript has a usage like `console.log("statement", object);` it feels natural to use such statements in logging.
Have a nice day.

**Comment by gillyb** [comment]
Ok, thanks for the suggestion. I'll add it as an issue, and work on it soon.
(Issue created : #11)
