### ISSUE TITLE
Documentation regarding the Logger Option "callback" is misleading.

### ISSUE THREAD

**Issue by srsa-kevin** [logzio/logzio-nodejs#131]
### Describe the documentation issue

In the readme of the project, the callback option is given this description: "A callback function called when an unrecoverable error has occured in the logger. The function API is: function(err) - err being the Error object.".

However, this is not how the source code seems to operate. Instead, the callback is called when there is an error, and is called with the error as an argument, OR is called on success, and does not include any arguments in the callback.

This impacted my team, as we were logging "errors" when sending logs via the logger "failed" according to the callback.

### Suggested Fix

The readme should give a more clear explanation as to the function of the callback option and when/how it is used.

**Comment by yotamloe** [comment]
@srsa-kevin Thanks for reporting this issue, and I'm sorry to hear it impacted your team. I opened a new pr to update the callback option documentation.

**Comment by yotamloe** [comment]
@srsa-kevin please feel free to reopen this issue if needed, or to give us any other feedback

**Comment by srsa-kevin** [comment]
@yotamloe the updated docs look great! Thanks for the quick turnaround on this.
