### ISSUE TITLE
sendAndClose Method Had Stopped Working

### ISSUE THREAD

**Issue by barakhaim** [logzio/logzio-nodejs#17]
Hi,

The sendAndClose Method  is not working any more.
When calling it the data is logged but the process doesn't end...
I had to revert back to my branch. 
It  seems that one of your recent changes broke this functionality.

--Barak

**Comment by gillyb** [comment]
Hi @barakhaim, 
I'm very sorry about that. You're right - it was a bug caused by the previous pull request. I just committed a fix to it, and also bumped the version in npm
