### ISSUE TITLE
Bunyan transporter?

### ISSUE THREAD

**Issue by raubas** [logzio/logzio-nodejs#20]
We are using Bunyan - do you have a transporter for Bunyan as well? (Did see the one regarding Winston..)

**Comment by gillyb** [comment]
Hey @raubas - Unfortunately we don't have a transporter for Bunyan yet. It's on our 'to do' list, but hard to say yet when it will be ready.

**Comment by raubas** [comment]
Aight, do you have any insight on which of your other transporters that might be useful in the meantime - had a look at just using curl as a cronjob..?

**Comment by asafm** [comment]
Are you emitting JSONs or plain test to stdout?
I think Filebeat is currently the best choice. We have a really good guide
in our Log Shipping section at app.logz.io
Also support will gladly help you out - you can reach it through our online
chat and email.

**Comment by gillyb** [comment]
You can reach our log shipping section directly here : https://app.logz.io/#/dashboard/data-sources/Filebeat
