### ISSUE TITLE
Not working well with AWS Lambda

### ISSUE THREAD

**Issue by hlandao** [logzio/logzio-nodejs#21]
It seems that running an AWS Lambda (with the winston-logzio-node transport), causes the Lambda function to always be timed-out.

Was anyone able to make that work ?

Thanks!

**Comment by gillyb** [comment]
Hey @hlandao ,
Are you using this repository https://github.com/logzio/winston-logzio ? (Let's move this issue to the correct repo)
If so, what is the code you put in your lambda function ?

**Comment by hlandao** [comment]
@gillyb yes, using: https://github.com/logzio/winston-logzio so we can move there.

```
const winston = require('winston');
const logzioWinstonTransport = require('winston-logzio');

const createLoggerFromContext = (context, jobId, level, extraParams) => {

  extraParams = extraParams || {}

  const loggerOptions = {
    token: 'xxx',
    host: 'listener.logz.io',
    name: `${context.functionName}`,
    level
  };


  const logger = new winston.Logger({
    level,
    rewriters: [
      (level, msg, meta) => {
        meta = meta || {};
        meta =  Object.assign(meta, extraParams, {jobId})
        return meta;
      }
    ]
  });

  logger.add(logzioWinstonTransport, loggerOptions);
  logger.add(winston.transports.Console, {level});

  return logger;
}
```

Lambdas are constantly timed-out.
Thx!

**Comment by froyke** [comment]
For anyone looking at this thread.
The standard logger has a `sendAndClose()` method.
Without it it'll keep waiting on its internal timer.
Didn't check if the winston logger has a similar capability.

To team Logz.io - I recommend updating your sample in the README file and include this - as currently when running as a console app - it spins forever :(

**Comment by AlonMiz** [comment]
We have updated the readme with this note, thanks.
