### ISSUE TITLE
Add an option to disable proxy

### ISSUE THREAD

**Issue by gajus** [logzio/logzio-nodejs#23]
You are using `request` package which itself uses `HTTP_RPOXY` environment variable to configure HTTP proxy to use. In the particular case of proxies, this is bad – I don't want logs to flood our internal proxies.

Add an option to explicitly disable use of any proxy for the logging transport.

**Comment by gillyb** [comment]
Hey @gajus ,
Sorry for the belated response. I looked at the `request` module a bit, and it seems like there isn't an option to override the `HTTP_PROXY` setting for a single request.
So the right way to deal with this would be to set the `NO_PROXY` environment variable with the domain the logs are being sent to. This will tell `request` to not use the proxy configured for all requests to our domain. The domain we use in the log shipper is `listener.logz.io:8070` for http.
If you're using https then it's `listener.logz.io:8071` and if you have the UDP parameter set then you need to set this domain `listener.logz.io:5050`.

The relevant spot in the documentation can be found here : https://www.npmjs.com/package/request#controlling-proxy-behaviour-using-environment-variables

Hope that helps!

**Comment by gajus** [comment]
Thats useful. Thank you.

**Comment by gillyb** [comment]
Great, Happy I helped. :)
