### ISSUE TITLE
Ability to specify destination port

### ISSUE THREAD

**Issue by sempasha** [logzio/logzio-nodejs#25]
For those users who are behind firewall it will be useful to get an ability to send logs messages on common http ports, like `80` for plain HTTP and `443` for HTTPS. Seems that listener.logz.io ready to accept bulk logs via HTTPS on port `443`.

Lets say it will `port` option of `createLogger` method, what you think about?

**Comment by AlonMiz** [comment]
you can now specify custom port and listener,
look at the updated readme.
