### ISSUE TITLE
BUG: objects are lost

### ISSUE THREAD

**Issue by zatziky** [logzio/logzio-nodejs#35]
If you try to log a message containing objects then logz.io doesn't show these logs in Kibana.

### How to reproduce it
```
var logger = require('logzio-nodejs').createLogger({
  token: 'process.env.LOGZ_IO_TOKEN',
  type: 'YourLogType',   
  debug: true
});

logger.log({message: 'string'}); // ok
logger.log({message: {a: 'object'}}); // LOST
logger.log({message: {a: 'object', b: {c: 2}}}); // LOST
logger.log({message: ['array']}); // ok
logger.log({message: ['number', 1]}); // ok
logger.log({message: ['number', 1, {a: 'object', b: {c: 2}}]}); // LOST
logger.log({message: "['the whole log is a string', 1, {a: 'object', b: {c: 2}}]"}); // ok
```
I verified that this lib actually sends the parsed objects. It seems like Logz.io servers can't parse the incoming requests. The lib [logzio-nodejs](https://github.com/logzio/logzio-nodejs/issues/new)` sends the requests using `request.post(options, function (err, res, body) {` from `LogzioLogger.prototype._send`. The `options.body` contains all data: 

> {"message":"This is a log message","type":"YourLogType","@timestamp":"2018-03-21T12:19:15.440Z"}
> {"message":"string","type":"YourLogType","@timestamp":"2018-03-21T12:19:15.440Z"}
> {"message":{"a":"object"},"type":"YourLogType","@timestamp":"2018-03-21T12:19:15.440Z"}
> {"message":{"a":"object","b":{"c":2}},"type":"YourLogType","@timestamp":"2018-03-21T12:19:15.440Z"}
> {"message":["array"],"type":"YourLogType","@timestamp":"2018-03-21T12:19:15.440Z"}
> {"message":["number",1],"type":"YourLogType","@timestamp":"2018-03-21T12:19:15.440Z"}
> {"message":["number",1,{"a":"object","b":{"c":2}}],"type":"YourLogType","@timestamp":"2018-03-21T12:19:15.440Z"}
> {"message":"['the whole log is a string', 1, {a: 'object', b: {c: 2}}]","type":"YourLogType","@timestamp":"2018-03-21T12:27:21.962Z"}

### Actual result
This is a screen shot from [kibana](https://app.logz.io/#/dashboard/kibana). All logs containing objects are **not logged**.
![image](https://user-images.githubusercontent.com/2794365/37709255-f204fb24-2d09-11e8-845c-89dbf68ed19c.png)

### Expected result
[Kibana](https://app.logz.io/#/dashboard/kibana) should display also the logs for objects from the code snippet:
- logger.log({message: {a: 'object'}}); // LOST
- logger.log({message: {a: 'object', b: {c: 2}}}); // LOST
- logger.log({message: ['number', 1, {a: 'object', b: {c: 2}}]}); // LOST

**Comment by zatziky** [comment]
If you use `JSON.stringify()` then you get a better result. I still believe it is a bug. The logs shouldn't ever get lost OR at least the lib should warn you that they will not be logged if you send them in "a way".

![image](https://user-images.githubusercontent.com/2794365/37710180-250167f8-2d0d-11e8-8430-75499df9d30b.png)


```
logger.log({message: JSON.stringify('string')});
logger.log({message: JSON.stringify({a: 'object'})});
logger.log({message: JSON.stringify({a: 'object', b: {c: 2}})});
logger.log({message: JSON.stringify(['array'])});
logger.log({message: JSON.stringify(['number', 1])});
logger.log({message: JSON.stringify(['number', 1, {a: 'object', b: {c: 2}}])});
logger.log({message: JSON.stringify("['the whole log is a string', 1, {a: 'object', b: {c: 2}}]")});
```

**Comment by zatziky** [comment]
Just a guess but I believe that this is the problematic part:

```
LogzioLogger.prototype._messagesToBody = function(msgs) {
    var body = '';
    for (var i = 0; i < msgs.length; i++) {
        body = body + jsonToString(msgs[i]) + '\n';
    }
    return body;
};
```

**Comment by meytalGuetta** [comment]
Hi @zatziky,

The message field is a special field that already mapped as text type. If you want to send log which containing an object you can use a different field name.

You do get an exception message in Kibana 
![screen shot 2018-04-23 at 14 50 04](https://user-images.githubusercontent.com/29204949/39125003-33dd2b96-4706-11e8-9f03-36e71bf8f245.png)
