### ISSUE TITLE
Suppport CORS handling in sending http request

### ISSUE THREAD

**Issue by tomyitav** [logzio/logzio-nodejs#36]
When logging from my angular app, I get a 'no Access-control-allow-origin' message. (Even though the message is sent to my logzio account). 

![erroroncors2](https://user-images.githubusercontent.com/16193919/41874570-efaa63ec-78d0-11e8-9436-d0f6c7e60c9f.PNG)

It would be nice if setting headers could be configured when creating the logger.

**Comment by AlonMiz** [comment]
Hi Tom,
This shipper is intended to ship logs with a node js app, and not directly from a browser.
you can redirect logs into your app server and send them from your actual server with the relevant log appender
EDIT
Actually, there should not be an alternative, as the library I mentioned (before the edit) is deprecated and it will reveal your token publicly.
