### ISSUE TITLE
Line 45 is incorrect - should stringify 'json' ,not 'msg

### ISSUE THREAD

**Issue by yosidahan** [logzio/logzio-nodejs#4]
var jsonToString = exports.jsonToString = function(json) {
    try {
        return JSON.stringify(json);
    }
    catch(ex) {
        return stringifySafe(msg, null, null, function() { }); <<<<<------ Exception
    }
};

**Comment by gillyb** [comment]
Thanks yosi, fixing this now.
Sorry for the bug :/

**Comment by gillyb** [comment]
This was fixed already :) Thanks again for reporting
