### ISSUE TITLE
@timestamp_nano multiple issues

### ISSUE THREAD

**Issue by lorf** [logzio/logzio-nodejs#40]
1. `@timestamp_nano` can't be used to compare timestamps of two different shippers, because `hrtime()`, used by `@timestamp_nano`,  is relative to a process start time. So the order of log messages, sorted by `@timestamp_nano`, will be wrong when several shippers are involved.

2. When converting `hrtime()` timestamp to a `@timestamp_nano` string, the integers are not left-padded with zeroes, this leads to errors when comparing resulting strings alphabetically (e.g. 1234 will be less than 567 when compared alphabetically). This will cause sorting errors.

**Comment by idohalevi** [comment]
@lorf 
I merged your docker pr. Did it help?

**Comment by lorf** [comment]
@idohalevi Yes, I'm running with shipper with that change and it works better at least.

**Comment by idohalevi** [comment]
@lorf 
Glad to hear, I will add the above it to my todo list and hope to provide a solution quick

**Comment by ronish31** [comment]
Fixed in https://github.com/logzio/logzio-nodejs/pull/79
