### ISSUE TITLE
_defaultCallback is called unbound

### ISSUE THREAD

**Issue by matanlb** [logzio/logzio-nodejs#45]
Package Version: 0.4.16

We've been working until recently with v0.4.2, since the last auto-update (we do that for patch version) in some scenarios (simples one is no token) the following error will be thrown.

```
'TypeError: Cannot read property \'log\' of undefined',
     '    at LogzioLogger._defaultCallback (/Users/matan/git/bookmd/client/node_modules/logzio-nodejs/lib/logzio-nodejs.js:102:28)',
     '    at Request._callback (/Users/matan/git/bookmd/client/node_modules/logzio-nodejs/lib/logzio-nodejs.js:315:21)',
     '    at Request.self.callback (/Users/matan/git/bookmd/client/node_modules/request/request.js:185:22)',
     '    at emitTwo (events.js:106:13)',
     '    at Request.emit (events.js:191:7)',
     '    at Request.<anonymous> (/Users/matan/git/bookmd/client/node_modules/request/request.js:1161:10)',
     '    at emitOne (events.js:96:13)',
     '    at Request.emit (events.js:188:7)',
     '    at IncomingMessage.<anonymous> (/Users/matan/git/bookmd/client/node_modules/request/request.js:1083:12)',
     '    at IncomingMessage.g (events.js:291:16)',
     '    at emitNone (events.js:91:20)',
     '    at IncomingMessage.emit (events.js:185:7)',
     '    at endReadableNT (_stream_readable.js:974:12)',
     '    at _combinedTickCallback (internal/process/next_tick.js:74:11)',
     '    at process._tickDomainCallback (internal/process/next_tick.js:122:9)'
```

Multiple places in the package perform the following action:
`var callback = this.callback` or `this.callback = this._defaultCallback` which causes the method to become unbound and when `this.internalLogger.log('logzio-logger error: ' + err, err);` is called an error is thrown.

This did not happen in the older version since it used console.log directly. The only usage of this in the older context was `if (err && !this.supressErrors)` so I assume the supressErrors check never had an effect (when called from unbound context).

**Comment by idohalevi** [comment]
@matanlb 
Thank you for the help :)
I will take a look and update.

**Comment by idohalevi** [comment]
#47 - should solve the issue

**Comment by idohalevi** [comment]
@matanlb  can you please confirm that the latest version solved the bug?

**Comment by whostolebenfrog** [comment]
I'm not the bug creator but updating resolves this issue for us.

**Comment by idohalevi** [comment]
@whostolebenfrog 
thank you! :)
