### ISSUE TITLE
Winston Transport?

### ISSUE THREAD

**Issue by SidBala** [logzio/logzio-nodejs#5]
We are extensively using winston in our application code. I suspect a lot of people are.

Is there a winston-transport wrapper for Logz.io? Any plans to make one in the near future?

**Comment by virtser** [comment]
+1

**Comment by gillyb** [comment]
We're working on a winston transport wrapper. It will be released soon. :)

**Comment by gillyb** [comment]
We just published a winston transport.
Feel free to try, and give us relevant feedback :)

Check it out : https://github.com/logzio/winston-logzio
