### ISSUE TITLE
unable to close server in mocha tests

### ISSUE THREAD

**Issue by fuzzy-logic** [logzio/logzio-nodejs#61]
In api test using mocha, last step after tests have run is to shutdown the nodejs server with:

     after(function (done) {
          server.close(done);
     })

however, with any script that has require('logzio-nodejs'); this does not shutdown the server as presumably some resources eg; sockets must still be in use.

**Comment by idohalevi** [comment]
@fuzzy-logic Can you provide an example of how you use `logzio-nodejs` in your tests?

**Comment by fuzzy-logic** [comment]
Hi, thanks for the response.

My test is a REST API endpoint test that does require('app,js') and starts an http server. , so it's how logzio-nodejs is used in the app, which is like so:


    logzio = require('logzio-nodejs').createLogger({
        token: 'xxxxxxxx',
        type: 'beapi',
        protocol: 'https',
        host: 'listener-eu.logz.io',
        numberOfRetries: 3,
        bufferSize: 10,
        timeout: 1000,
        port: '8071'
    });


But on server.close() in the test to end the test, as long as logzio-nodejs has been required in the application, the server will not shutdown gracefully, only way round is to comment out the require() if NODE_ENV=local_test.  Presumably this is because logzio-nodejs has an open socket to the logzio servers?

Perhaps there's a way to force logzio-nodejs to close any open sockets?

I did try to use sendAndClose() but was still unable to close the server.

**Comment by fuzzy-logic** [comment]
ah have found a work around, in app.js have added a server.shutdown() method.

server.shutdown = function(callback) {
  console.log'server.shutdown() called. Attempting graceful shutdown');
  new Promise((resolve, reject) => {
    try {
      console.log('app server shutting down closing logger');
      logzioLogger.close(resolve);
    } catch (err) {
      console.log('error shutting down logger');
      console.dir(err);
      reject(err);
    }
  }).then(function(data) {
    console.log('app server close...');
    server.close(callback);
  }).catch(function(e) {
      console.log('There was a problem shutting down app server gracefully');
  })
}

Then in the mocha test:

     after(function (done) {
          console.log("All tests finished shutdown server.");
          server.shutdown(done);
     })
