### ISSUE TITLE
Typing is incorrect for sendAndClose method

### ISSUE THREAD

**Issue by gsvarovsky** [logzio/logzio-nodejs#83]
The sendAndClose type is given as
```typescript
    sendAndClose(callback: (error: Error, bulk: object) => void): void;
```

The callback parameter should be optional.

**Comment by ronish31** [comment]
@gsvarovsky
Will be fixed soon, thank you

**Comment by ronish31** [comment]
https://github.com/logzio/logzio-nodejs/pull/85

Updated.
