### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by duvillierA** [logzio/logzio-nodejs#9]
hi,

Is it a way to send a tag relative to a log?

Thanks

**Comment by gillyb** [comment]
hey @duvillierA - Not sure i understand what you mean ? What would be considered a tag ?
You can send an object instead of just a message, and then put which ever properties you wish on the object.

**Comment by gillyb** [comment]
@duvillierA - Is this still relevant to you ?

**Comment by duvillierA** [comment]
@gillyb nop
